name: '@primer/publish'
description: 'Publish Primer projects to npm with GitHub Design Systems conventions'
inputs:
  releaseBranch:
    description: 'Branch that releases should be cut from (usually your default branch)'
    required: false
  dir:
    description: "directory to find package.json in"
    required: false
  dryRun:
    description: "run action without publishing"
    required: false
  npmArgs:
    description: "publish options & additional npm cli arguments"
    required: false
  releaseTag:
    description: 'Override tag to release package with'
    required: false
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'