name: '@primer/publish'
description: 'Publish Primer projects to npm with GitHub Design Systems conventions'
inputs:
  dir:
    description: "directory to find package.json in"
    required: false
  dry-run:
    description: "run action without publishing"
    required: false
  npm-args:
    description: "publish options & additional npm cli arguments"
    required: false
  release-branch:
    description: 'Branch that releases should be cut from (usually your default branch)'
    required: false
    default: 'master'
  release-tag:
    description: 'Override tag to release package with'
    required: false
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.npm-args}}